// 0: INIT
// 10: MANUAL
// 20: AUTO
// 30: ERRORR
static %PC0% : INT;

case %PC0% of
    0:
        if "INIT"() then
            %PC0% := 10;
        end_if;;
    10:
        %PC0% := 20;
        ;
    20:
        %PC0% := 30;
        ;
    30:
        %PC0% := 40;
        ;
    40:
        %PC0% := 50;
        ;
    50:
        %PC0% := 60;
        ;
    60:
        %PC0% := 70;
        ;
    70:
        %PC0% := 80;
        ;
    80:
        %PC0% := 90;
        ;
    90:
        %PC0% := 100;
        ;
end_case;
